// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc1
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaxosService_PerformTransaction_FullMethodName         = "/paxos.PaxosService/PerformTransaction"
	PaxosService_Prepare_FullMethodName                    = "/paxos.PaxosService/Prepare"
	PaxosService_Accept_FullMethodName                     = "/paxos.PaxosService/Accept"
	PaxosService_Commit_FullMethodName                     = "/paxos.PaxosService/Commit"
	PaxosService_GetBalance_FullMethodName                 = "/paxos.PaxosService/GetBalance"
	PaxosService_UpdateServerState_FullMethodName          = "/paxos.PaxosService/UpdateServerState"
	PaxosService_SendCatchUpData_FullMethodName            = "/paxos.PaxosService/SendCatchUpData"
	PaxosService_GetLocalLogs_FullMethodName               = "/paxos.PaxosService/GetLocalLogs"
	PaxosService_GetMainBlocks_FullMethodName              = "/paxos.PaxosService/GetMainBlocks"
	PaxosService_GetPerformance_FullMethodName             = "/paxos.PaxosService/GetPerformance"
	PaxosService_GetClientBalanceFromServer_FullMethodName = "/paxos.PaxosService/GetClientBalanceFromServer"
)

// PaxosServiceClient is the client API for PaxosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Paxos Service definition, containing the necessary RPC calls.
type PaxosServiceClient interface {
	// Initiates a transaction between two servers.
	PerformTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	// Proposes a transaction to reach consensus via Paxos.
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error)
	// Sends the decision on whether to accept or reject a proposal.
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBalance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BalanceResponse, error)
	UpdateServerState(ctx context.Context, in *StateUpdateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendCatchUpData(ctx context.Context, in *CatchUpRequest, opts ...grpc.CallOption) (*CatchUpResponse, error)
	GetLocalLogs(ctx context.Context, in *GetLocalLogsRequest, opts ...grpc.CallOption) (*GetLocalLogsResponse, error)
	GetMainBlocks(ctx context.Context, in *GetMainBlocksRequest, opts ...grpc.CallOption) (*GetMainBlocksResp, error)
	GetPerformance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PerformanceResponse, error)
	GetClientBalanceFromServer(ctx context.Context, in *GetClientBalFromServerReq, opts ...grpc.CallOption) (*GetClientBalFromServerRes, error)
}

type paxosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosServiceClient(cc grpc.ClientConnInterface) PaxosServiceClient {
	return &paxosServiceClient{cc}
}

func (c *paxosServiceClient) PerformTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, PaxosService_PerformTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, PaxosService_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptResponse)
	err := c.cc.Invoke(ctx, PaxosService_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) GetBalance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, PaxosService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) UpdateServerState(ctx context.Context, in *StateUpdateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosService_UpdateServerState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) SendCatchUpData(ctx context.Context, in *CatchUpRequest, opts ...grpc.CallOption) (*CatchUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatchUpResponse)
	err := c.cc.Invoke(ctx, PaxosService_SendCatchUpData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) GetLocalLogs(ctx context.Context, in *GetLocalLogsRequest, opts ...grpc.CallOption) (*GetLocalLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocalLogsResponse)
	err := c.cc.Invoke(ctx, PaxosService_GetLocalLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) GetMainBlocks(ctx context.Context, in *GetMainBlocksRequest, opts ...grpc.CallOption) (*GetMainBlocksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMainBlocksResp)
	err := c.cc.Invoke(ctx, PaxosService_GetMainBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) GetPerformance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceResponse)
	err := c.cc.Invoke(ctx, PaxosService_GetPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) GetClientBalanceFromServer(ctx context.Context, in *GetClientBalFromServerReq, opts ...grpc.CallOption) (*GetClientBalFromServerRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientBalFromServerRes)
	err := c.cc.Invoke(ctx, PaxosService_GetClientBalanceFromServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosServiceServer is the server API for PaxosService service.
// All implementations must embed UnimplementedPaxosServiceServer
// for forward compatibility.
//
// Paxos Service definition, containing the necessary RPC calls.
type PaxosServiceServer interface {
	// Initiates a transaction between two servers.
	PerformTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
	// Proposes a transaction to reach consensus via Paxos.
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	Accept(context.Context, *AcceptRequest) (*AcceptResponse, error)
	// Sends the decision on whether to accept or reject a proposal.
	Commit(context.Context, *CommitRequest) (*emptypb.Empty, error)
	GetBalance(context.Context, *emptypb.Empty) (*BalanceResponse, error)
	UpdateServerState(context.Context, *StateUpdateRequest) (*emptypb.Empty, error)
	SendCatchUpData(context.Context, *CatchUpRequest) (*CatchUpResponse, error)
	GetLocalLogs(context.Context, *GetLocalLogsRequest) (*GetLocalLogsResponse, error)
	GetMainBlocks(context.Context, *GetMainBlocksRequest) (*GetMainBlocksResp, error)
	GetPerformance(context.Context, *emptypb.Empty) (*PerformanceResponse, error)
	GetClientBalanceFromServer(context.Context, *GetClientBalFromServerReq) (*GetClientBalFromServerRes, error)
	mustEmbedUnimplementedPaxosServiceServer()
}

// UnimplementedPaxosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaxosServiceServer struct{}

func (UnimplementedPaxosServiceServer) PerformTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerformTransaction not implemented")
}
func (UnimplementedPaxosServiceServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPaxosServiceServer) Accept(context.Context, *AcceptRequest) (*AcceptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedPaxosServiceServer) Commit(context.Context, *CommitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPaxosServiceServer) GetBalance(context.Context, *emptypb.Empty) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedPaxosServiceServer) UpdateServerState(context.Context, *StateUpdateRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServerState not implemented")
}
func (UnimplementedPaxosServiceServer) SendCatchUpData(context.Context, *CatchUpRequest) (*CatchUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCatchUpData not implemented")
}
func (UnimplementedPaxosServiceServer) GetLocalLogs(context.Context, *GetLocalLogsRequest) (*GetLocalLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocalLogs not implemented")
}
func (UnimplementedPaxosServiceServer) GetMainBlocks(context.Context, *GetMainBlocksRequest) (*GetMainBlocksResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMainBlocks not implemented")
}
func (UnimplementedPaxosServiceServer) GetPerformance(context.Context, *emptypb.Empty) (*PerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerformance not implemented")
}
func (UnimplementedPaxosServiceServer) GetClientBalanceFromServer(context.Context, *GetClientBalFromServerReq) (*GetClientBalFromServerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientBalanceFromServer not implemented")
}
func (UnimplementedPaxosServiceServer) mustEmbedUnimplementedPaxosServiceServer() {}
func (UnimplementedPaxosServiceServer) testEmbeddedByValue()                      {}

// UnsafePaxosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosServiceServer will
// result in compilation errors.
type UnsafePaxosServiceServer interface {
	mustEmbedUnimplementedPaxosServiceServer()
}

func RegisterPaxosServiceServer(s grpc.ServiceRegistrar, srv PaxosServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaxosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaxosService_ServiceDesc, srv)
}

func _PaxosService_PerformTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).PerformTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_PerformTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).PerformTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).Accept(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).GetBalance(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_UpdateServerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).UpdateServerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_UpdateServerState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).UpdateServerState(ctx, req.(*StateUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_SendCatchUpData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatchUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).SendCatchUpData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_SendCatchUpData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).SendCatchUpData(ctx, req.(*CatchUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_GetLocalLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).GetLocalLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_GetLocalLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).GetLocalLogs(ctx, req.(*GetLocalLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_GetMainBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMainBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).GetMainBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_GetMainBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).GetMainBlocks(ctx, req.(*GetMainBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_GetPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).GetPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_GetPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).GetPerformance(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_GetClientBalanceFromServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientBalFromServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).GetClientBalanceFromServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_GetClientBalanceFromServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).GetClientBalanceFromServer(ctx, req.(*GetClientBalFromServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PaxosService_ServiceDesc is the grpc.ServiceDesc for PaxosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaxosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.PaxosService",
	HandlerType: (*PaxosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PerformTransaction",
			Handler:    _PaxosService_PerformTransaction_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _PaxosService_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _PaxosService_Accept_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _PaxosService_Commit_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _PaxosService_GetBalance_Handler,
		},
		{
			MethodName: "UpdateServerState",
			Handler:    _PaxosService_UpdateServerState_Handler,
		},
		{
			MethodName: "SendCatchUpData",
			Handler:    _PaxosService_SendCatchUpData_Handler,
		},
		{
			MethodName: "GetLocalLogs",
			Handler:    _PaxosService_GetLocalLogs_Handler,
		},
		{
			MethodName: "GetMainBlocks",
			Handler:    _PaxosService_GetMainBlocks_Handler,
		},
		{
			MethodName: "GetPerformance",
			Handler:    _PaxosService_GetPerformance_Handler,
		},
		{
			MethodName: "GetClientBalanceFromServer",
			Handler:    _PaxosService_GetClientBalanceFromServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
